In [1]:
import openai
openai.api_key = "設定open api key"# set your API key -> https://platform.openai.com/account/api-keys

- prepare

In [2]:
leetcode_all_database_2021=["175. Combine Two Tables",
                            "176. Second Highest Salary",
                            "177. Nth Highest Salary",
                            "178. Rank Scores",
                            "179. Consecutive Numbers",
                            "180. Employees Earning More Than Their Managers",
                            "181. Duplicate Emails",
                            "182. Customers Who Never Order",
                            "183. Delete Duplicate Emails",
                            "184. Rising Temperature",
                            "185. Trips and Users",
                            "186. Game Play Analysis I",
                            "187. Game Play Analysis II",
                            "188. Game Play Analysis III",
                            "189. Game Play Analysis IV",
                            "190. Median Employee Salary",
                            "191. Managers with at Least 5 Direct Reports",
                            "192. Find Median Given Frequency of Numbers",
                            "193. Winning Candidate",
                            "194. Employee Bonus",
                            "195. Get Highest Answer Rate Question",
                            "196. Find Cumulative Salary of an Employee",
                            "197. Count Student Number in Departments",
                            "198. Find Customer Referee",
                            "199. Investment in Equity",
                            "200. Customer Placing the Largest Number of Orders",
                            "201. Big Countries",
                            "202. Classes More Than 5 Students",
                            "203. Friend Requests I: Overall Acceptance Rate",
                            "204. Human Traffic of Stadium",
                            "205. Friend Requests II: Who Has the Most Friends",
                            "206. Consecutive Available Seats",
                            "207. Sales Person",
                            "208. Tree Node",
                            "209. Triangle Judgement",
                            "210. Shortest Distance in a Plane",
                            "211. Shortest Distance in a Line",
                            "212. Second Degree Follower",
                            "213. Average Salary: Departments VS Company",
                            "214. Students Report By Geography",
                            "215. Biggest Single Number",
                            "216. Not Boring Movies",
                            "217. Exchange Seats",
                            "218. Swap Salary",
                            "219. Customers Who Bought Products A and B but Not C",
                            "220. Actors and Directors Who Cooperated At Least Three Times",
                            "221. Height Checker",
                            "222. Grumpy Bookstore Owner",
                            "223. Product Sales Analysis I",
                            "224. Product Sales Analysis II",
                            "225. Product Sales Analysis III",
                            "226. Project Employees I",
                            "227. Project Employees II",
                            "228. Sales Analysis I",
                            "229. Sales Analysis II",
                            "230. Game Play Analysis V",
                            "231. New Users Daily Count",
                            "232. Highest Grade For Each Student",
                            "233. Reported Posts",
                            "234. Active Businesses",
                            "235. User Activity for the Past 30 Days I",
                            "236. User Activity for the Past 30 Days II",
                            "237. Article Views I",
                            "238. Article Views II",
                            "239. Market Analysis I",
                            "240. Market Analysis II",
                            ]

- function for leet code problem(Chinese)

In [3]:

def getLeetCodeContent(each_question):
    """
    each_question: The numb of target question:  "175. Combine Two Tables"
    response: Leetcode problem content from OpenAI(text-davinci-003)
    """
    # prompt = "請給我LeetCode {question number}. {question title}的題目，包含：Table、Example、Output、Explanation的內容"
    prompt = f"請給我LeetCode {each_question}的題目，包含：Input的所有Table、Output的Table、以及每個Example裡Input及Output的Table、Explanation的內容，總之100%還原leetcode題目內容"
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=2000,
        # n=1,
        # stop=None,
        top_p=1.0,
        temperature=0.1,
    )
    return response


def getLeetCodeSolution(each_question):
    """
    each_question: The numb of target question:  "175. Combine Two Tables"
    response: Leetcode solution from OpenAI(text-davinci-003)
    """
    # prompt = "請給我LeetCode {question number}. {question title}的題目，包含：Table、Example、Output、Explanation的內容"
    prompt = f"請給我LeetCode {each_question}的解答，要能夠在LeetCode上精準通過的MySQL程式碼，我只要程式碼，其他不要"
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=1000,
        # n=1,
        # stop=None,
        top_p=1.0,
        temperature=0.5,
    )
    return response

- test function

In [4]:
# Problem content & Solution
problem_content=getLeetCodeContent(leetcode_all_database_2021[0])
print(problem_content.choices[0].text)


problem_solution=getLeetCodeSolution(leetcode_all_database_2021[0])
print(problem_solution.choices[0].text)

## 175. Combine Two Tables

### Problem
Table: `Person`

| Column Name | Type    |
| ----------- | ------- |
| PersonId    | int     |
| FirstName   | varchar |
| LastName    | varchar |

Table: `Address`

| Column Name | Type    |
| ----------- | ------- |
| AddressId   | int     |
| PersonId    | int     |
| City        | varchar |
| State       | varchar |

Write a SQL query for a report that provides the following information for each person in the Person table, regardless if there is an address for each of those people:

- FirstName
- LastName
- City
- State

### Example

Person table:

| PersonId | FirstName | LastName |
| -------- | --------- | -------- |
| 1        | John      | Doe      |
| 2        | Bob       | Smith    |

Address table:

| AddressId | PersonId | City  | State |
| --------- | -------- | ----- | ----- |
| 1         | 1        | New York City | NY |
| 2         | 2        | Boston | MA    |

Result table:

| FirstName | LastName | City      | State |
| --------- | -------- | --------- | ----- |
| John      | Doe      | New York City | NY   |
| Bob       | Smith    | Boston    | MA    |

### Explanation
We can use a `LEFT JOIN` to join the `Person` and `Address` tables. This will return all rows from the `Person` table, and any matching rows from the `Address` table. If there is no match, the columns from the `Address` table will be filled with `NULL` values.

```
SELECT p.FirstName, p.LastName, a.City, a.State
FROM Person p
LEFT JOIN Address a
    ON p.PersonId = a.PersonId;
```


```sql
SELECT
    Person.FirstName,
    Person.LastName,
    Address.City,
    Address.State
FROM Person
LEFT JOIN Address
    ON Person.PersonId = Address.PersonId;
```

# Test.2 use loop to get each LeetCode Problem's content and solution.

In [5]:
# use three problems for testing.
leetcode_all_database_2021=["175. Combine Two Tables",
                            "176. Second Highest Salary",
                            "177. Nth Highest Salary",
                            ]

In [6]:
for each_question in leetcode_all_database_2021:
    # Problem content & Solution
    problem_content=getLeetCodeContent(each_question)
    # print(problem_content.choices[0].text)


    problem_solution=getLeetCodeSolution(each_question)
    # print(problem_solution.choices[0].text)
    
    # content & solution
    content=problem_content.choices[0].text+problem_solution.choices[0].text
    print(content)
    # save to txt
    leetcode_database_problem="LeetCode_DataBase_"+each_question+".txt"
    with open(leetcode_database_problem, "w") as f:
        f.write(content)
    # print(each_question)

## 175. Combine Two Tables

### Problem
Table: `Person`

| Column Name | Type    |
| ----------- | ------- |
| PersonId    | int     |
| FirstName   | varchar |
| LastName    | varchar |

Table: `Address`

| Column Name | Type    |
| ----------- | ------- |
| AddressId   | int     |
| PersonId    | int     |
| City        | varchar |
| State       | varchar |

Write a SQL query for a report that provides the following information for each person in the Person table, regardless if there is an address for each of those people:

- FirstName
- LastName
- City
- State

### Example

**Input**

Person table:

| PersonId | FirstName | LastName |
| -------- | --------- | -------- |
| 1        | John      | Doe      |
| 2        | Bob       | Smith    |

Address table:

| AddressId | PersonId | City    | State |
| --------- | -------- | ------- | ----- |
| 1         | 1        | New York| NY    |
| 2         | 2        | Boston  | MA    |

**Output**

| FirstName | LastName | City    | State |
| --------- | -------- | ------- | ----- |
| John      | Doe      | New York| NY    |
| Bob       | Smith    | Boston  | MA    |

### Explanation

We can use an `INNER JOIN` to join the `Person` and `Address` tables on the `PersonId` column. This will give us all the people who have an address. We can then use a `LEFT JOIN` to join the `Person` and `Address` tables on the `PersonId` column. This will give us all the people, regardless if they have an address or not.

SELECT
    Person.FirstName,
    Person.LastName,
    Address.City,
    Address.State
FROM Person
LEFT JOIN Address
    ON Person.PersonId = Address.PersonId


## 176. Second Highest Salary

### Problem

Write a SQL query to get the second highest salary from the `Employee` table.

### Table: Employee

| Id | Salary |
|----|--------|
| 1  | 100    |
| 2  | 200    |
| 3  | 300    |

### Example

#### Input

| Id | Salary |
|----|--------|
| 1  | 100    |
| 2  | 200    |
| 3  | 300    |

#### Output

| SecondHighestSalary |
|---------------------|
| 200                 |

### Explanation

Given the above `Employee` table, the second highest salary is `200`.

```sql
SELECT MAX(Salary) AS SecondHighestSalary
FROM Employee
WHERE Salary < (SELECT MAX(Salary) FROM Employee)
```


## 177. Nth Highest Salary

### Table: Employee

| Id | Salary |
|----|-------|
| 1  | 100   |
| 2  | 200   |
| 3  | 300   |

### Output Table:

| NthHighestSalary |
|------------------|

### Example 1

#### Input

```
Table: Employee

Id	Salary
1	100
2	200
3	300

N = 2
```

#### Output

```
NthHighestSalary
200
```

### Example 2

#### Input

```
Table: Employee

Id	Salary
1	100
2	200
3	300

N = 1
```

#### Output

```
NthHighestSalary
300
```

### Explanation

Write a SQL query to get the nth highest salary from the `Employee` table.

```
SELECT MAX(Salary) AS NthHighestSalary
FROM Employee
WHERE (SELECT COUNT(DISTINCT Salary) FROM Employee WHERE Salary >= e.Salary) >= N
```

```sql
SELECT
  (SELECT DISTINCT Salary
   FROM Employee
   ORDER BY Salary DESC
   LIMIT N-1, 1) AS NthHighestSalary
```

# Entire code

In [ ]:
# leetcode_all_database_2021=["175. Combine Two Tables",
#                             "176. Second Highest Salary",
#                             "177. Nth Highest Salary",
#                             "178. Rank Scores",
#                             "179. Consecutive Numbers",
#                             "180. Employees Earning More Than Their Managers",
#                             "181. Duplicate Emails",
#                             "182. Customers Who Never Order",
#                             "183. Delete Duplicate Emails",
#                             "184. Rising Temperature",
#                             "185. Trips and Users",
#                             "186. Game Play Analysis I",
#                             "187. Game Play Analysis II",
#                             "188. Game Play Analysis III",
#                             "189. Game Play Analysis IV",
#                             "190. Median Employee Salary",
#                             "191. Managers with at Least 5 Direct Reports",
#                             "192. Find Median Given Frequency of Numbers",
#                             "193. Winning Candidate",
#                             "194. Employee Bonus",
#                             "195. Get Highest Answer Rate Question",
#                             "196. Find Cumulative Salary of an Employee",
#                             "197. Count Student Number in Departments",
#                             "198. Find Customer Referee",
#                             "199. Investment in Equity",
#                             "200. Customer Placing the Largest Number of Orders",
#                             "201. Big Countries",
#                             "202. Classes More Than 5 Students",
#                             "203. Friend Requests I: Overall Acceptance Rate",
#                             "204. Human Traffic of Stadium",
#                             "205. Friend Requests II: Who Has the Most Friends",
#                             "206. Consecutive Available Seats",
#                             "207. Sales Person",
#                             "208. Tree Node",
#                             "209. Triangle Judgement",
#                             "210. Shortest Distance in a Plane",
#                             "211. Shortest Distance in a Line",
#                             "212. Second Degree Follower",
#                             "213. Average Salary: Departments VS Company",
#                             "214. Students Report By Geography",
#                             "215. Biggest Single Number",
#                             "216. Not Boring Movies",
#                             "217. Exchange Seats",
#                             "218. Swap Salary",
#                             "219. Customers Who Bought Products A and B but Not C",
#                             "220. Actors and Directors Who Cooperated At Least Three Times",
#                             "221. Height Checker",
#                             "222. Grumpy Bookstore Owner",
#                             "223. Product Sales Analysis I",
#                             "224. Product Sales Analysis II",
#                             "225. Product Sales Analysis III",
#                             "226. Project Employees I",
#                             "227. Project Employees II",
#                             "228. Sales Analysis I",
#                             "229. Sales Analysis II",
#                             "230. Game Play Analysis V",
#                             "231. New Users Daily Count",
#                             "232. Highest Grade For Each Student",
#                             "233. Reported Posts",
#                             "234. Active Businesses",
#                             "235. User Activity for the Past 30 Days I",
#                             "236. User Activity for the Past 30 Days II",
#                             "237. Article Views I",
#                             "238. Article Views II",
#                             "239. Market Analysis I",
#                             "240. Market Analysis II",
#                             ]
# for each_question in leetcode_all_database_2021:
#     # Problem content & Solution
#     problem_content=getLeetCodeContent(each_question)
#     # print(problem_content.choices[0].text)


#     problem_solution=getLeetCodeSolution(each_question)
#     # print(problem_solution.choices[0].text)
    
#     # content & solution
#     content=problem_content.choices[0].text+problem_solution.choices[0].text
#     print(content)
#     # save to txt
#     leetcode_database_problem="LeetCode_DataBase_"+each_question+".txt"
#     with open(leetcode_database_problem, "w") as f:
#         f.write(content)
#     # print(each_question)